pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)\.m2\repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

steps:
  - task: Cache@2
    inputs:
      key: 'maven | "$(Agent.OS)"'
      path: $(MAVEN_CACHE_FOLDER)
    displayName: 'Cache Maven local repo'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.12'
      jdkArchitectureOption: 'x64'
      mavenOptions: '-Xmx3072m --no-transfer-progress $(MAVEN_OPTS)'
      goals: 'package'